services:
  gateway:
    container_name: gateway
    image: request-queue
    ports:
      - "80:8080"
    depends_on:
      - lambda1
      - lambda2

  lambda1:
    container_name: lambda1
    image: lambda
    platform: linux/amd64
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 512M
        reservations:
          cpus: "1"
          memory: 512M

  lambda2:
    container_name: lambda2
    image: lambda
    platform: linux/amd64
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 512M
        reservations:
          cpus: "1"
          memory: 512M
